name: "Imorph vigilant build"
description: "Github action to deploy site to imorph"
author: "Anurag Kumar <anurag@imorph.io>"
inputs:
  buildDir:
    required: false
    description: "Build dir to publish on imorph"
    default: "/dist"
  imorphSecret:
    required: false
    description: "Imorph secret"
    default: ${{ secrets.IMORPH_SECRET }}
  imorphDomain:
    required: false
    description: "Imorph domain"
    default: ${{ secrets.IMORPH_DOMAIN }}
runs:
  using: "node16"
  pre: "lib/pre.js"
  main: "lib/main.js"
  post: "lib/post.js"
