name: "Imorph vigilant build"
description: "Github action to deploy site to imorph"
author: "Anurag Kumar <anurag@imorph.io>"
inputs:
  buildDir:
    required: false
    description: "Build dir to publish on imorph"
    default: "/dist"
  imorphSecret:
    required: false
    description: "Imorph secret"
  imorphDomain:
    required: false
    description: "Imorph domain"
branding:
  icon: "upload-cloud"
  color: "green"
runs:
  using: "node16"
  pre: "dist/pre.js"
  main: "dist/main.js"
  post: "dist/post.js"
