name: "Imorph vigilant build"
description: "Github action to deploy site to imorph"
author: "Anurag Kumar <anurag@imorph.io>"
inputs:
  buildDir:
    required: false
    description: "Build dir to publish on imorph"
runs:
  using: "node16"
  pre: "dist/index.js"
  main: "dist/index.js"
  post: "dist/index.js"
